In [70]:
import numpy as np
x=np.asarray([1,2,3,4,5,6])
len(x)
np.vander(x,increasing=False)

array([[   1,    1,    1,    1,    1,    1],
       [  32,   16,    8,    4,    2,    1],
       [ 243,   81,   27,    9,    3,    1],
       [1024,  256,   64,   16,    4,    1],
       [3125,  625,  125,   25,    5,    1],
       [7776, 1296,  216,   36,    6,    1]])

In [69]:
import numpy as np
def ivander(arr):#arr=[1,2,3,4,5]
    N,f=len(arr),[]
    for i in range(N):    
        x,p=[],arr[i]    
        for j in range(N):        
            x.append(p**(N-j-1))    
        f.append(x)
    return np.array(f)

print(ivander([1,2,3,4,5,6]))

[[   1    1    1    1    1    1]
 [  32   16    8    4    2    1]
 [ 243   81   27    9    3    1]
 [1024  256   64   16    4    1]
 [3125  625  125   25    5    1]
 [7776 1296  216   36    6    1]]
